### PR TITLE
Unlinked anomaly - PR 317

### PR DESCRIPTION
**Pull request by mailtesting244**
#### Ticket Type
		  
- [] Feature
- [] Bug
- [] Task
		  
#### Feature/Ticket Status

- [] Partial (NOT ready for QA)
- [] Complete (READY for QA or are there more PRs coming?))

#### External Ticket Link (i.e. Jira)

Paste the URL on a new line:

### CODE REVIEW

**Review by mikewe910 — APPROVED** [review]
[1m] dfsf

**Review by mikewe910 — CHANGES_REQUESTED** [review]
fdg

**Review by mikewe910 — CHANGES_REQUESTED** [review]
[1m] fd

**Review by mikewe910 — APPROVED** [review]
[1m] fdg

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
sdfsd[1h]

**Review by mikewe910 — APPROVED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Pull request closed without merging**
