### PR TITLE
Update example.js[1m]

### PR DESCRIPTION
**Pull request by mainusamocvety**
#### Ticket Type	  
- [] Feature
- [] Bug
- [] Task
		  
#### Feature/Ticket Status
- [] Partial (Not Ready for QA)
- [] Complete (Ready for QA)

### CODE REVIEW

**Review by mailtesting244 — APPROVED** [review]
[1m]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
fdgd

**Review by MikeSpedicy — APPROVED** [review]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[1m]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[1m]

**Review by MikeSpedicy — DISMISSED** [review]

**Pull request closed without merging**
