### PR TITLE
PR 210 [20h10m]

### PR DESCRIPTION
**Pull request by mailtesting244**
[x] Feature
[x] Database Schema
https://changecaptain.atlassian.net/browse/SEAL-941

### CODE REVIEW

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
change

**Review by MikeSpedicy — APPROVED** [review]
32d[1h]appr

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[2m] req change

**Review by mainusamocvety — APPROVED** [review]
another user

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
change[2m]

**Review by MikeSpedicy — APPROVED** [review]
appr [2m]

**Pull request merged**
