### PR TITLE
PR 330 - Missing CC ticket anomaly

### PR DESCRIPTION
**Pull request by MikeSpedicy**
#### Ticket Type
		  
- [] Feature
- [] Bug
- [x] Task
		  
#### Feature/Ticket Status

- [] Partial (NOT ready for QA)
- [] Complete (READY for QA or are there more PRs coming?))

#### External Ticket Link (i.e. Jira)

Paste the URL on a new line:
https://changecaptain.atlassian.net/browse/SEAL-1587

### CODE REVIEW

**Review by mailtesting244 — APPROVED** [review]
[1m]

**Review by mailtesting244 — APPROVED** [review]
[1m]

**Review by mailtesting244 — APPROVED** [review]
[1m]

**Review by mainusamocvety — APPROVED** [review]

**Review by mainusamocvety — CHANGES_REQUESTED** [review]
dfgdrfg

**Review by mikewe910 — CHANGES_REQUESTED** [review]
[1m]

**Pull request closed without merging**
