### PR TITLE
PR 565 - unlinked user

### PR DESCRIPTION
**Pull request by mailtesting244**
#### Ticket Type	  
- [] Feature
- [] Bug
- [] Task
		  
#### Feature/Ticket Status
- [] Partial (Not Ready for QA)
- [] Complete (Ready for QA)

#### External Ticket Link (i.e. Jira) - Paste link on a new line below:z
https://changecaptain.atlassian.net/browse/SEAL-1841

### CODE REVIEW

**Review by mikewe910 — APPROVED** [review]
[1m]

**Review by mikewe910 — APPROVED** [review]

**Review by mikewe910 — CHANGES_REQUESTED** [review]
[1m]

**Review by mikewe910 — CHANGES_REQUESTED** [review]
fdg

**Review by mikewe910 — APPROVED** [review]

**Review by developchangecaptain — APPROVED** [review]
[1m]

**Pull request merged**
