### PR TITLE
PR 577 - Missed Ticket Type

### PR DESCRIPTION
**Pull request by mailtesting244**
#### Ticket Type	  
- [] Feature
- [x] Bug
- [] Task
		  
#### Feature/Ticket Status
- [] Partial (Not Ready for QA)
- [] Complete (Ready for QA)

### CODE REVIEW

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by mainusamocvety — APPROVED** [review]
[1m]

**Review by mainusamocvety — CHANGES_REQUESTED** [review]
[1m]

**Review by mainusamocvety — CHANGES_REQUESTED** [review]
[1m]

**Review by mainusamocvety — APPROVED** [review]
[1m]

**Pull request merged**
