### PR TITLE
PR 293

### PR DESCRIPTION
**Pull request by mailtesting244**
#### Ticket Type
		  
- [] Feature
- [x] Bug
- [] Task
		  
#### Feature/Ticket Status

- [] Partial (NOT ready for QA)
- [x] Complete (READY for QA or are there more PRs coming?))

#### External Ticket Link (i.e. Jira)

Paste the URL on a new line:
https://changecaptain.atlassian.net/browse/SEAL-679

### CODE REVIEW

**Review by MikeSpedicy — APPROVED** [review]
[1h]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[1m]

**Review by mainusamocvety — APPROVED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]
[1m]fg h

**Review by MikeSpedicy — APPROVED** [review]
[1m]fg h

**Review by MikeSpedicy — APPROVED** [review]

**Pull request merged**
