### PR TITLE
PR 530 - Unlinked user

### PR DESCRIPTION
**Pull request by MikeSpedicy**
#### Ticket Type	  
- [] Feature
- [] Bug
- [] Task
		  
#### Feature/Ticket Status
- [] Partial (Not Ready for QA)
- [] Complete (Ready for QA)

### CODE REVIEW

**Review by mailtesting244 — APPROVED** [review]
[1m]

**Review by mikewe910 — CHANGES_REQUESTED** [review]
[1m]

**Review by mikewe910 — APPROVED** [review]
[1m]

**Review by mikewe910 — DISMISSED** [review]
[1m]

**Review by mikewe910 — APPROVED** [review]

**Pull request closed without merging**
