### PR TITLE
PR 190 [19h]

### PR DESCRIPTION
**Pull request by mailtesting244**
[x] Task
[x] Database Schema
https://changecaptain.atlassian.net/browse/SEAL-725

### CODE REVIEW

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
change req[2m]

**Review by mainusamocvety — APPROVED** [review]
appr[2m]

**Review by mainusamocvety — APPROVED** [review]
1

**Review by MikeSpedicy — APPROVED** [review]
qw

**Pull request merged**
