### PR TITLE
PR 192 [19h2m]

### PR DESCRIPTION
**Pull request by mikewe910**
[x] Task
[x] Database Schema
https://changecaptain.atlassian.net/browse/SEAL-1

### CODE REVIEW

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[2m]

**Review by mailtesting244 — APPROVED** [review]
rtg[2h]

**Review by MikeSpedicy — APPROVED** [review]
dgf[1m]

**Review by mailtesting244 — APPROVED** [review]
[1m]

**Pull request merged**
