### PR TITLE
PR 580 - unlinked user

### PR DESCRIPTION
**Pull request by mailtesting244**
#### Ticket Type	  
- [x] Feature
- [] Bug
- [] Task
		  
#### Feature/Ticket Status
- [] Partial (Not Ready for QA)
- [] Complete (Ready for QA)

#### External Ticket Link (i.e. Jira) - Paste link on a new line below:
https://unique.atlassian.net/browse/UNIQ-3

### CODE REVIEW

**Review by mikewe910 — APPROVED** [review]
[1m]

**Review by mikewe910 — CHANGES_REQUESTED** [review]
fgdhf

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]

**Review by mikewe910 — CHANGES_REQUESTED** [review]
cxv

**Pull request closed without merging**
