### PR TITLE
Update README.md[1m]

### PR DESCRIPTION
**Pull request by mailtesting244**
#### Ticket Type
		  
- [] Feature
- [x] Bug
- [] Task
		  
#### Feature/Ticket Status

- [] Partial (NOT ready for QA)
- [] Complete (READY for QA or are there more PRs coming?))

#### External Ticket Link (i.e. Jira)

Paste the URL on a new line:
https://changecaptain.atlassian.net/browse/SEAL-1537

### CODE REVIEW

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by mainusamocvety — APPROVED** [review]
[11m]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by MikeSpedicy — APPROVED** [review]
[1m]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[1m]

**Review by MikeSpedicy — CHANGES_REQUESTED** [review]
[1m]

**Pull request merged**
